language: c
compiler:
- clang
- gcc
env:
- COVERAGE=true
- COVERAGE=false;
matrix:
  exclude:
  - compiler: clang
    env: COVERAGE=true
  - compiler: gcc
    env: COVERAGE=false
before_install:
- sudo pip install cpp-coveralls
- wget http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.tar.gz  -O /tmp/cmake.tar.gz
- tar xzf /tmp/cmake.tar.gz
- export PATH=$PWD/cmake-3.2.1-Linux-x86_64/bin/:$PATH
script:
- ./build.sh all test
after_success:
- if [[ $COVERAGE == 'true' ]]; then ./coverage.sh; cd build && make package_source; fi

